In [1]:
import pandas as pd
import json 
df = pd.read_json("data.json")
df

       0    1    2    3    4               5
0      1  5.1  3.5  1.4  0.2     Iris-setosa
1      2  4.9  3.0  1.4  0.2     Iris-setosa
2      3  4.7  3.2  1.3  0.2     Iris-setosa
3      4  4.6  3.1  1.5  0.2     Iris-setosa
4      5  5.0  3.6  1.4  0.2     Iris-setosa
..   ...  ...  ...  ...  ...             ...
145  146  6.7  3.0  5.2  2.3  Iris-virginica
146  147  6.3  2.5  5.0  1.9  Iris-virginica
147  148  6.5  3.0  5.2  2.0  Iris-virginica
148  149  6.2  3.4  5.4  2.3  Iris-virginica
149  150  5.9  3.0  5.1  1.8  Iris-virginica

[150 rows x 6 columns]

In [2]:
df.head()

   0    1    2    3    4            5
0  1  5.1  3.5  1.4  0.2  Iris-setosa
1  2  4.9  3.0  1.4  0.2  Iris-setosa
2  3  4.7  3.2  1.3  0.2  Iris-setosa
3  4  4.6  3.1  1.5  0.2  Iris-setosa
4  5  5.0  3.6  1.4  0.2  Iris-setosa

In [3]:
df.tail()

       0    1    2    3    4               5
145  146  6.7  3.0  5.2  2.3  Iris-virginica
146  147  6.3  2.5  5.0  1.9  Iris-virginica
147  148  6.5  3.0  5.2  2.0  Iris-virginica
148  149  6.2  3.4  5.4  2.3  Iris-virginica
149  150  5.9  3.0  5.1  1.8  Iris-virginica