In [1]:
import pandas as pd

In [8]:
df = pd.read_csv("Mental health Depression disorder Data.csv")

C:\Users\pc\AppData\Local\Temp\ipykernel_26672\2256141925.py:1: DtypeWarning: Columns (5,6) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("Mental health Depression disorder Data.csv")

In [ ]:
df.head()

,index,Year,Period,Avg hrs per day sleeping,Standard Error,Type of Days,Age Group,Activity,Sex
0,0,2003,Annual,8.57,0.018,All days,15 years and over,Sleeping,Both
1,1,2004,Annual,8.55,0.026,All days,15 years and over,Sleeping,Both
2,2,2005,Annual,8.62,0.023,All days,15 years and over,Sleeping,Both
3,3,2006,Annual,8.63,0.024,All days,15 years and over,Sleeping,Both
4,4,2007,Annual,8.57,0.024,All days,15 years and over,Sleeping,Both

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 689 entries, 0 to 688
Data columns (total 16 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   b       689 non-null    object
 1   30.83   689 non-null    object
 2   0       689 non-null    float64
 3   u       689 non-null    object
 4   g       689 non-null    object
 5   w       689 non-null    object
 6   v       689 non-null    object
 7   1.25    689 non-null    float64
 8   t       689 non-null    object
 9   t.1     689 non-null    object
 10  01      689 non-null    int64
 11  f       689 non-null    object
 12  g.1     689 non-null    object
 13  00202   689 non-null    object
 14  0.1     689 non-null    int64
 15  +       689 non-null    object
dtypes: float64(2), int64(2), object(12)
memory usage: 86.3+ KB

In [20]:
df.describe()

                0        1.25          01            0.1
count  689.000000  689.000000  689.000000     689.000000
mean     4.765631    2.224819    2.402032    1018.862119
std      4.978470    3.348739    4.866180    5213.743149
min      0.000000    0.000000    0.000000       0.000000
25%      1.000000    0.165000    0.000000       0.000000
50%      2.750000    1.000000    0.000000       5.000000
75%      7.250000    2.625000    3.000000     396.000000
max     28.000000   28.500000   67.000000  100000.000000

In [9]:
df = pd.read_csv("Time Americans Spend Sleeping.csv")

In [10]:
df.head()

,index,Year,Period,Avg hrs per day sleeping,Standard Error,Type of Days,Age Group,Activity,Sex
0,0,2003,Annual,8.57,0.018,All days,15 years and over,Sleeping,Both
1,1,2004,Annual,8.55,0.026,All days,15 years and over,Sleeping,Both
2,2,2005,Annual,8.62,0.023,All days,15 years and over,Sleeping,Both
3,3,2006,Annual,8.63,0.024,All days,15 years and over,Sleeping,Both
4,4,2007,Annual,8.57,0.024,All days,15 years and over,Sleeping,Both

In [11]:
df = pd.read_csv("clean_dataset.csv")

In [12]:
df.head()

,Gender,Age,Debt,Married,BankCustomer,Industry,Ethnicity,YearsEmployed,PriorDefault,Employed,CreditScore,DriversLicense,Citizen,ZipCode,Income,Approved
0,1,30.83,0.000,1,1,Industrials,White,1.25,1,1,1,0,ByBirth,202,0,1
1,0,58.67,4.460,1,1,Materials,Black,3.04,1,1,6,0,ByBirth,43,560,1
2,0,24.50,0.500,1,1,Materials,Black,1.50,1,0,0,0,ByBirth,280,824,1
3,1,27.83,1.540,1,1,Industrials,White,3.75,1,1,5,1,ByBirth,100,3,1
4,1,20.17,5.625,1,1,Industrials,White,1.71,1,0,0,0,ByOtherMeans,120,0,1

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 689 entries, 0 to 688
Data columns (total 16 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   b       689 non-null    object
 1   30.83   689 non-null    object
 2   0       689 non-null    float64
 3   u       689 non-null    object
 4   g       689 non-null    object
 5   w       689 non-null    object
 6   v       689 non-null    object
 7   1.25    689 non-null    float64
 8   t       689 non-null    object
 9   t.1     689 non-null    object
 10  01      689 non-null    int64
 11  f       689 non-null    object
 12  g.1     689 non-null    object
 13  00202   689 non-null    object
 14  0.1     689 non-null    int64
 15  +       689 non-null    object
dtypes: float64(2), int64(2), object(12)
memory usage: 86.3+ KB

In [18]:
df.describe()

                0        1.25          01            0.1
count  689.000000  689.000000  689.000000     689.000000
mean     4.765631    2.224819    2.402032    1018.862119
std      4.978470    3.348739    4.866180    5213.743149
min      0.000000    0.000000    0.000000       0.000000
25%      1.000000    0.165000    0.000000       0.000000
50%      2.750000    1.000000    0.000000       5.000000
75%      7.250000    2.625000    3.000000     396.000000
max     28.000000   28.500000   67.000000  100000.000000

In [13]:
df = pd.read_csv("crx.csv")

In [14]:
df.head()

   b  30.83      0  u  g  w  v  1.25  t t.1  01  f g.1  00202  0.1  +
0  a  58.67  4.460  u  g  q  h  3.04  t   t   6  f   g  00043  560  +
1  a  24.50  0.500  u  g  q  h  1.50  t   f   0  f   g  00280  824  +
2  b  27.83  1.540  u  g  w  v  3.75  t   t   5  t   g  00100    3  +
3  b  20.17  5.625  u  g  w  v  1.71  t   f   0  f   s  00120    0  +
4  b  32.08  4.000  u  g  m  v  2.50  t   f   0  t   g  00360    0  +

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 689 entries, 0 to 688
Data columns (total 16 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   b       689 non-null    object
 1   30.83   689 non-null    object
 2   0       689 non-null    float64
 3   u       689 non-null    object
 4   g       689 non-null    object
 5   w       689 non-null    object
 6   v       689 non-null    object
 7   1.25    689 non-null    float64
 8   t       689 non-null    object
 9   t.1     689 non-null    object
 10  01      689 non-null    int64
 11  f       689 non-null    object
 12  g.1     689 non-null    object
 13  00202   689 non-null    object
 14  0.1     689 non-null    int64
 15  +       689 non-null    object
dtypes: float64(2), int64(2), object(12)
memory usage: 86.3+ KB

In [16]:
df.describe()

                0        1.25          01            0.1
count  689.000000  689.000000  689.000000     689.000000
mean     4.765631    2.224819    2.402032    1018.862119
std      4.978470    3.348739    4.866180    5213.743149
min      0.000000    0.000000    0.000000       0.000000
25%      1.000000    0.165000    0.000000       0.000000
50%      2.750000    1.000000    0.000000       5.000000
75%      7.250000    2.625000    3.000000     396.000000
max     28.000000   28.500000   67.000000  100000.000000

The dataset provides a yearly overview of how much time adults spend sleeping on average per day, along with demographic and statistical details. It is useful for analyzing sleep trends over time.

This dataset contains numerical and categorical encoded features describing different observations. Some columns represent numerical measurements, while others contain letter codes representing categorical attributes. The dataset also includes ID-like fields. Each row corresponds to one recorded instance.

This dataset contains mixed data types (numerical + categorical codes), where each row likely corresponds to one entity or observation. The values represent multiple characteristics or measurements, but the meaning of the columns requires a data dictionary to fully interpret.